# Generated by Django 6.0.2 on 2026-05-08 10:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('RBSE', 'RBSE'), ('ICSE', 'ICSE'), ('IB', 'IB'), ('STATE', 'State Board'), ('OTHER', 'Other')], default='CBSE', max_length=100)),
                ('medium', models.CharField(choices=[('ENGLISH', 'English'), ('HINDI', 'Hindi'), ('BOTH', 'Hindi & English')], default='ENGLISH', max_length=100)),
                ('established_year', models.PositiveIntegerField()),
                ('primary_image', models.ImageField(upload_to='schools/')),
                ('description', models.TextField(blank=True, null=True)),
                ('full_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('school_type', models.CharField(choices=[('PLAY', 'Play School'), ('PRIMARY', 'Primary School'), ('PUBLIC', 'Public School'), ('SECONDARY', 'Secondary School'), ('SENIOR_SECONDARY', 'Senior Secondary School')], default='SENIOR_SECONDARY', max_length=100)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('admission_last_date', models.DateField()),
                ('admission_open', models.BooleanField(default=True)),
                ('mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid 10 digit mobile number', regex='^[6-9]\\d{9}$')])),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('school_time', models.CharField(max_length=100)),
                ('visiting_hours', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'indexes': [models.Index(fields=['school_name'], name='schools_school__a6a93e_idx'), models.Index(fields=['city'], name='schools_city_63b57a_idx'), models.Index(fields=['board'], name='schools_board_ee14fa_idx'), models.Index(fields=['school_type'], name='schools_school__eef8c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.school')),
            ],
            options={
                'verbose_name': 'Admission Required Document',
                'verbose_name_plural': 'Admission Required Documents',
                'db_table': 'admission_required_docs',
            },
        ),
        migrations.CreateModel(
            name='SchoolFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='app.school')),
            ],
            options={
                'verbose_name': 'School Facility',
                'verbose_name_plural': 'School Facilities',
                'db_table': 'school_facilities',
            },
        ),
        migrations.CreateModel(
            name='SchoolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.school')),
            ],
            options={
                'verbose_name': 'School Image',
                'verbose_name_plural': 'School Images',
                'db_table': 'school_images',
            },
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('aadhar_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Enter valid 12 digit Aadhar number', regex='^\\d{12}$')])),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('cast_category', models.CharField(choices=[('GENERAL', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('OTHER', 'OTHER')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('apply_class', models.CharField(choices=[('PLAYGROUP', 'Playgroup'), ('NURSERY', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('PREP', 'Prep'), ('CLASS_1', 'Class 1'), ('CLASS_2', 'Class 2'), ('CLASS_3', 'Class 3'), ('CLASS_4', 'Class 4'), ('CLASS_5', 'Class 5'), ('CLASS_6', 'Class 6'), ('CLASS_7', 'Class 7'), ('CLASS_8', 'Class 8'), ('CLASS_9', 'Class 9'), ('CLASS_10', 'Class 10'), ('CLASS_11_SCIENCE', 'Class 11 (Science)'), ('CLASS_11_COMMERCE', 'Class 11 (Commerce)'), ('CLASS_11_HUMANITIES', 'Class 11 (Humanities)'), ('CLASS_11_AGRICULTURE', 'Class 11 (Agriculture)'), ('CLASS_12_SCIENCE', 'Class 12 (Science)'), ('CLASS_12_COMMERCE', 'Class 12 (Commerce)'), ('CLASS_12_HUMANITIES', 'Class 12 (Humanities)'), ('CLASS_12_AGRICULTURE', 'Class 12 (Agriculture)')], max_length=30)),
                ('previous_school_name', models.CharField(blank=True, max_length=255)),
                ('previous_board', models.CharField(blank=True, max_length=100)),
                ('last_class_attended', models.CharField(blank=True, max_length=50)),
                ('year_of_passing', models.PositiveIntegerField(blank=True, null=True)),
                ('father_name', models.CharField(max_length=255)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_mobile', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter valid 10 digit mobile number', regex='^[6-9]\\d{9}$')])),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_income', models.CharField(blank=True, choices=[('BELOW_2', 'Below ₹2 Lakhs'), ('2_TO_5', '₹2 Lakhs - ₹5 Lakhs'), ('5_TO_10', '₹5 Lakhs - ₹10 Lakhs'), ('10_TO_15', '₹10 Lakhs - ₹15 Lakhs'), ('ABOVE_15', 'Above ₹15 Lakhs')], max_length=20)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_mobile', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter valid 10 digit mobile number', regex='^[6-9]\\d{9}$')])),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('declaration_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.school')),
            ],
            options={
                'verbose_name': 'Student Application',
                'verbose_name_plural': 'Student Applications',
                'db_table': 'student_applications',
            },
        ),
    ]
