# Generated by Django 6.0.2 on 2026-05-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_school_affiliation_number_school_campus_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfacility',
            name='icon_class',
            field=models.CharField(default='fas fa-school', max_length=100),
        ),
    ]
