# Generated by Django 6.0.2 on 2026-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_schoolfacility_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='application_no',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
