# Generated by Django 6.0.2 on 2026-05-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_studentapplication_application_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='nationality',
        ),
    ]
