# Generated by Django 6.0.2 on 2026-05-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_studentapplication_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='father_income',
            field=models.CharField(blank=True, choices=[('Below ₹2 Lakhs', 'Below ₹2 Lakhs'), ('2 Lakhs - ₹5 Lakhs', '₹2 Lakhs - ₹5 Lakhs'), ('₹5 Lakhs - ₹10 Lakhs', '₹5 Lakhs - ₹10 Lakhs'), ('₹10 Lakhs - ₹15 Lakhs', '₹10 Lakhs - ₹15 Lakhs'), ('Above ₹15 Lakhs', 'Above ₹15 Lakhs')], max_length=100),
        ),
    ]
