# Generated by Django 6.0.2 on 2026-05-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_studentapplication_father_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='affiliation_number',
            field=models.CharField(blank=True, help_text='Enter valid affiliation number (e.g. 1730123)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='campus_size',
            field=models.CharField(blank=True, help_text='Example: 8 Acres / 1200 Sq. meters', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='student_teacher_ratio',
            field=models.CharField(blank=True, help_text='Enter ratio in format like 25:1', max_length=20, null=True),
        ),
    ]
