# Generated by Django 6.0.2 on 2026-05-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_school_affiliation_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
