# Generated by Django 6.0.2 on 2026-05-27 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='affiliation_number',
            field=models.CharField(blank=True, help_text='Enter valid affiliation number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='medium',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('HINDI', 'Hindi'), ('Hindi & English', 'Hindi & English')], default='ENGLISH', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='aadhar_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid 12 digit Aadhar number', regex='^[2-9]{1}[0-9]{11}$')]),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(fields=('school_name', 'city'), name='unique_school_per_city'),
        ),
    ]
