# Generated by Django 6.0.2 on 2026-05-27 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_school_affiliation_number_alter_school_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='aadhar_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Enter valid 12 digit Aadhar number', regex='^[2-9]{1}[0-9]{11}$')]),
        ),
        migrations.AddConstraint(
            model_name='studentapplication',
            constraint=models.UniqueConstraint(fields=('school', 'aadhar_number'), name='unique_aadhar_per_school'),
        ),
    ]
