# Generated by Django 6.0.2 on 2026-05-29 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_studentapplication_father_income'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentapplication',
            name='unique_aadhar_per_school',
        ),
    ]
