# Generated by Django 6.0.2 on 2026-05-29 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_studentapplication_unique_aadhar_per_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter valid 10 digit mobile number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
